{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "47650ba4",
   "metadata": {
    "papermill": {
     "duration": 0.008974,
     "end_time": "2024-03-04T11:01:45.345186",
     "exception": false,
     "start_time": "2024-03-04T11:01:45.336212",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "## Overview of the DataSet\n",
    "\n",
    "SpaceX has gained worldwide attention for a series of historic milestones.\n",
    "\n",
    "It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.\n",
    "SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.\n",
    "\n",
    "Therefore if we can determine if the first stage will land, we can determine the cost of a launch.\n",
    "\n",
    "This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.\n",
    "\n",
    "This dataset includes a record for each payload carried during a SpaceX mission into outer space.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36670ffe",
   "metadata": {
    "papermill": {
     "duration": 0.008093,
     "end_time": "2024-03-04T11:01:45.361795",
     "exception": false,
     "start_time": "2024-03-04T11:01:45.353702",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Download the datasets\n",
    "\n",
    "This assignment requires you to load the spacex dataset.\n",
    "\n",
    "In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):\n",
    "\n",
    "<a href=\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01\" target=\"_blank\">Spacex DataSet</a>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df743641",
   "metadata": {
    "papermill": {
     "duration": 0.008937,
     "end_time": "2024-03-04T11:01:45.378990",
     "exception": false,
     "start_time": "2024-03-04T11:01:45.370053",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Store the dataset in database table\n",
    "\n",
    "**it is highly recommended to manually load the table using the database console LOAD tool in DB2**.\n",
    "\n",
    "<img src = \"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload.png\">\n",
    "\n",
    "Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the  dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new table as follows:\n",
    "\n",
    "**SPACEXDATASET**\n",
    "\n",
    "**Follow these steps while using old DB2 UI which is having Open Console Screen**\n",
    "\n",
    "**Note:While loading Spacex dataset, ensure that detect datatypes is disabled. Later click on the pencil icon(edit option).**\n",
    "\n",
    "1.  Change the Date Format by manually typing DD-MM-YYYY and timestamp format as DD-MM-YYYY HH\\:MM:SS.\n",
    "\n",
    "    Here you should place the cursor at Date field and manually type as DD-MM-YYYY.\n",
    "\n",
    "2.  Change the PAYLOAD_MASS\\_\\_KG\\_  datatype  to INTEGER.\n",
    "\n",
    "<img src = \"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload2.png\">\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "faaddc57",
   "metadata": {
    "papermill": {
     "duration": 0.007973,
     "end_time": "2024-03-04T11:01:45.395343",
     "exception": false,
     "start_time": "2024-03-04T11:01:45.387370",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "**Changes to be considered when having DB2 instance with the new UI having Go to UI screen**\n",
    "\n",
    "*   Refer to this insruction in this <a href=\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01\">link</a> for viewing  the new  Go to UI screen.\n",
    "\n",
    "*   Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.\n",
    "\n",
    "*   Later browse for the downloaded spacex file.\n",
    "\n",
    "<img src=\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png\" width=\"800\"/>\n",
    "\n",
    "*   Once done select the schema andload the file.\n",
    "\n",
    " <img src=\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png\" width=\"800\"/>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "614c6343",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:01:45.414339Z",
     "iopub.status.busy": "2024-03-04T11:01:45.413895Z",
     "iopub.status.idle": "2024-03-04T11:02:45.751071Z",
     "shell.execute_reply": "2024-03-04T11:02:45.749598Z"
    },
    "papermill": {
     "duration": 60.350349,
     "end_time": "2024-03-04T11:02:45.754031",
     "exception": false,
     "start_time": "2024-03-04T11:01:45.403682",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting sqlalchemy==1.3.9\r\n",
      "  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)\r\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.0/6.0 MB\u001b[0m \u001b[31m39.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l-\b \bdone\r\n",
      "\u001b[?25hBuilding wheels for collected packages: sqlalchemy\r\n",
      "  Building wheel for sqlalchemy (setup.py) ... \u001b[?25l-\b \b\\\b \bdone\r\n",
      "\u001b[?25h  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp310-cp310-linux_x86_64.whl size=1159827 sha256=53f2809dda67363c7688285e658cf21816f8cb48610931f00a09167abaeab2ee\r\n",
      "  Stored in directory: /root/.cache/pip/wheels/8b/6d/9c/e1793e5a2d85b89b8c362a4f0e3def54b786bcd14923b9ff00\r\n",
      "Successfully built sqlalchemy\r\n",
      "Installing collected packages: sqlalchemy\r\n",
      "  Attempting uninstall: sqlalchemy\r\n",
      "    Found existing installation: SQLAlchemy 2.0.25\r\n",
      "    Uninstalling SQLAlchemy-2.0.25:\r\n",
      "      Successfully uninstalled SQLAlchemy-2.0.25\r\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\r\n",
      "ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.\u001b[0m\u001b[31m\r\n",
      "\u001b[0mSuccessfully installed sqlalchemy-1.3.9\r\n",
      "Collecting ibm_db_sa\r\n",
      "  Downloading ibm_db_sa-0.4.0-py3-none-any.whl.metadata (5.3 kB)\r\n",
      "Requirement already satisfied: sqlalchemy>=0.7.3 in /opt/conda/lib/python3.10/site-packages (from ibm_db_sa) (1.3.9)\r\n",
      "Collecting ibm-db>=2.0.0 (from ibm_db_sa)\r\n",
      "  Downloading ibm_db-3.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)\r\n",
      "Downloading ibm_db_sa-0.4.0-py3-none-any.whl (31 kB)\r\n",
      "Downloading ibm_db-3.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.6 MB)\r\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m43.6/43.6 MB\u001b[0m \u001b[31m32.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: ibm-db, ibm_db_sa\r\n",
      "Successfully installed ibm-db-3.2.2 ibm_db_sa-0.4.0\r\n",
      "Requirement already satisfied: ipython-sql in /opt/conda/lib/python3.10/site-packages (0.5.0)\r\n",
      "Requirement already satisfied: prettytable in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (3.9.0)\r\n",
      "Requirement already satisfied: ipython in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (8.20.0)\r\n",
      "Collecting sqlalchemy>=2.0 (from ipython-sql)\r\n",
      "  Downloading SQLAlchemy-2.0.27-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)\r\n",
      "Requirement already satisfied: sqlparse in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (0.4.4)\r\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (1.16.0)\r\n",
      "Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (0.2.0)\r\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.9.0)\r\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.3)\r\n",
      "Requirement already satisfied: decorator in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (5.1.1)\r\n",
      "Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.19.1)\r\n",
      "Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.1.6)\r\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (3.0.42)\r\n",
      "Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (2.17.2)\r\n",
      "Requirement already satisfied: stack-data in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.6.2)\r\n",
      "Requirement already satisfied: traitlets>=5 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (5.9.0)\r\n",
      "Requirement already satisfied: exceptiongroup in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (1.2.0)\r\n",
      "Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (4.8.0)\r\n",
      "Requirement already satisfied: wcwidth in /opt/conda/lib/python3.10/site-packages (from prettytable->ipython-sql) (0.2.13)\r\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/lib/python3.10/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)\r\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.10/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)\r\n",
      "Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (2.0.1)\r\n",
      "Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (2.4.1)\r\n",
      "Requirement already satisfied: pure-eval in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)\r\n",
      "Downloading SQLAlchemy-2.0.27-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)\r\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.1/3.1 MB\u001b[0m \u001b[31m33.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: sqlalchemy\r\n",
      "  Attempting uninstall: sqlalchemy\r\n",
      "    Found existing installation: SQLAlchemy 1.3.9\r\n",
      "    Uninstalling SQLAlchemy-1.3.9:\r\n",
      "      Successfully uninstalled SQLAlchemy-1.3.9\r\n",
      "Successfully installed sqlalchemy-2.0.27\r\n"
     ]
    }
   ],
   "source": [
    "!pip install sqlalchemy==1.3.9\n",
    "!pip install ibm_db_sa\n",
    "!pip install ipython-sql"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0297e4a9",
   "metadata": {
    "papermill": {
     "duration": 0.013873,
     "end_time": "2024-03-04T11:02:45.781933",
     "exception": false,
     "start_time": "2024-03-04T11:02:45.768060",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Connect to the database\n",
    "\n",
    "Let us first load the SQL extension and establish a connection with the database\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "21a85567",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:45.811054Z",
     "iopub.status.busy": "2024-03-04T11:02:45.810636Z",
     "iopub.status.idle": "2024-03-04T11:02:47.085175Z",
     "shell.execute_reply": "2024-03-04T11:02:47.083915Z"
    },
    "papermill": {
     "duration": 1.292885,
     "end_time": "2024-03-04T11:02:47.088146",
     "exception": false,
     "start_time": "2024-03-04T11:02:45.795261",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "65f332b7",
   "metadata": {
    "papermill": {
     "duration": 0.013118,
     "end_time": "2024-03-04T11:02:47.115888",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.102770",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "**DB2 magic in case of old UI service credentials.**\n",
    "\n",
    "In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance before. From the **uri** field of your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://\n",
    "\n",
    "<img src =\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_edX/images/URI.jpg\">\n",
    "\n",
    "in the following format\n",
    "\n",
    "**%sql ibm_db_sa://my-username:my-password\\@my-hostname:my-port/my-db-name**\n",
    "\n",
    "**DB2 magic in case of new UI service credentials.**\n",
    "\n",
    "<img src =\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png\" width=600>  \n",
    "\n",
    "*   Use the following format.\n",
    "\n",
    "*   Add security=SSL at the end\n",
    "\n",
    "**%sql ibm_db_sa://my-username:my-password\\@my-hostname:my-port/my-db-name?security=SSL**\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "75f81f41",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:47.145733Z",
     "iopub.status.busy": "2024-03-04T11:02:47.144826Z",
     "iopub.status.idle": "2024-03-04T11:02:47.799725Z",
     "shell.execute_reply": "2024-03-04T11:02:47.798510Z"
    },
    "papermill": {
     "duration": 0.672683,
     "end_time": "2024-03-04T11:02:47.802634",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.129951",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ibm_db_dbi.py\", line 629, in connect\n",
      "    conn = ibm_db.connect(dsn, '', '', conn_options)\n",
      "Exception: [IBM][CLI Driver] SQL30082N  Security processing failed with reason \"24\" (\"USERNAME AND/OR PASSWORD INVALID\").  SQLSTATE=08001 SQLCODE=-30082\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3282, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 168, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 166, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 616, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ibm_db_dbi.py\", line 634, in connect\n",
      "    raise _get_exception(inst)\n",
      "ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: [IBM][CLI Driver] SQL30082N  Security processing failed with reason \"24\" (\"USERNAME AND/OR PASSWORD INVALID\").  SQLSTATE=08001 SQLCODE=-30082\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3258, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 2422, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 3282, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 168, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/impl.py\", line 166, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 616, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ibm_db_dbi.py\", line 634, in connect\n",
      "    raise _get_exception(inst)\n",
      "sqlalchemy.exc.OperationalError: (ibm_db_dbi.OperationalError) ibm_db_dbi::OperationalError: [IBM][CLI Driver] SQL30082N  Security processing failed with reason \"24\" (\"USERNAME AND/OR PASSWORD INVALID\").  SQLSTATE=08001 SQLCODE=-30082\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql ibm_db_sa://jjk92789:mUgin2bu22IbDNHE@125f9f61-9715-46f9-9399-c8177b21803b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:30426/bludb?security=SSL"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "38e120dc",
   "metadata": {
    "papermill": {
     "duration": 0.013878,
     "end_time": "2024-03-04T11:02:47.830604",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.816726",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "## Tasks\n",
    "\n",
    "Now write and execute SQL queries to solve the assignment tasks.\n",
    "\n",
    "### Task 1\n",
    "\n",
    "##### Display the names of the unique launch sites  in the space mission\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "24afaec6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:47.860777Z",
     "iopub.status.busy": "2024-03-04T11:02:47.859995Z",
     "iopub.status.idle": "2024-03-04T11:02:47.866670Z",
     "shell.execute_reply": "2024-03-04T11:02:47.865295Z"
    },
    "papermill": {
     "duration": 0.024426,
     "end_time": "2024-03-04T11:02:47.868991",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.844565",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select distinct Launch_Site from spacextbl"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b9b6b344",
   "metadata": {
    "papermill": {
     "duration": 0.013719,
     "end_time": "2024-03-04T11:02:47.896880",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.883161",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 2\n",
    "\n",
    "##### Display 5 records where launch sites begin with the string 'CCA'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4dc25d15",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:47.927275Z",
     "iopub.status.busy": "2024-03-04T11:02:47.926184Z",
     "iopub.status.idle": "2024-03-04T11:02:47.933390Z",
     "shell.execute_reply": "2024-03-04T11:02:47.932191Z"
    },
    "papermill": {
     "duration": 0.025163,
     "end_time": "2024-03-04T11:02:47.936011",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.910848",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select * from spacextbl where Launch_Site LIKE 'CCA%' limit 5;"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fbe6e29a",
   "metadata": {
    "papermill": {
     "duration": 0.013707,
     "end_time": "2024-03-04T11:02:47.963708",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.950001",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 3\n",
    "\n",
    "##### Display the total payload mass carried by boosters launched by NASA (CRS)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9ab94970",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:47.993413Z",
     "iopub.status.busy": "2024-03-04T11:02:47.992999Z",
     "iopub.status.idle": "2024-03-04T11:02:47.999099Z",
     "shell.execute_reply": "2024-03-04T11:02:47.998061Z"
    },
    "papermill": {
     "duration": 0.024449,
     "end_time": "2024-03-04T11:02:48.002183",
     "exception": false,
     "start_time": "2024-03-04T11:02:47.977734",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select sum(PAYLOAD_MASS__KG_) from spacextbl where Customer = 'NASA (CRS)'\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "17127a5b",
   "metadata": {
    "papermill": {
     "duration": 0.013849,
     "end_time": "2024-03-04T11:02:48.030113",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.016264",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 4\n",
    "\n",
    "##### Display average payload mass carried by booster version F9 v1.1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f1564fcf",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.059877Z",
     "iopub.status.busy": "2024-03-04T11:02:48.059490Z",
     "iopub.status.idle": "2024-03-04T11:02:48.066393Z",
     "shell.execute_reply": "2024-03-04T11:02:48.064994Z"
    },
    "papermill": {
     "duration": 0.02586,
     "end_time": "2024-03-04T11:02:48.069971",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.044111",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select avg(PAYLOAD_MASS__KG_) from spacextbl where Booster_Version LIKE 'F9 v1.1';\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1fa9d464",
   "metadata": {
    "papermill": {
     "duration": 0.014337,
     "end_time": "2024-03-04T11:02:48.098953",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.084616",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 5\n",
    "\n",
    "##### List the date when the first successful landing outcome in ground pad was acheived.\n",
    "\n",
    "*Hint:Use min function*\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "66a2c29a",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.129278Z",
     "iopub.status.busy": "2024-03-04T11:02:48.128883Z",
     "iopub.status.idle": "2024-03-04T11:02:48.135643Z",
     "shell.execute_reply": "2024-03-04T11:02:48.134514Z"
    },
    "papermill": {
     "duration": 0.025074,
     "end_time": "2024-03-04T11:02:48.138247",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.113173",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select min(Date) as min_date from spacextbl where Landing__Outcome = 'Success (ground pad)';"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0b6fd542",
   "metadata": {
    "papermill": {
     "duration": 0.014297,
     "end_time": "2024-03-04T11:02:48.166834",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.152537",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 6\n",
    "\n",
    "##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "60244f17",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.198014Z",
     "iopub.status.busy": "2024-03-04T11:02:48.197601Z",
     "iopub.status.idle": "2024-03-04T11:02:48.204420Z",
     "shell.execute_reply": "2024-03-04T11:02:48.203238Z"
    },
    "papermill": {
     "duration": 0.025442,
     "end_time": "2024-03-04T11:02:48.207155",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.181713",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select Booster_Version from spacextbl where (PAYLOAD_MASS__KG_> 4000 and PAYLOAD_MASS__KG_ < 6000) \n",
    "and (Landing__Outcome = 'Success (drone ship)');"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "433e8c9e",
   "metadata": {
    "papermill": {
     "duration": 0.014372,
     "end_time": "2024-03-04T11:02:48.235986",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.221614",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 7\n",
    "\n",
    "##### List the total number of successful and failure mission outcomes\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4fe216ba",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.266750Z",
     "iopub.status.busy": "2024-03-04T11:02:48.266296Z",
     "iopub.status.idle": "2024-03-04T11:02:48.273296Z",
     "shell.execute_reply": "2024-03-04T11:02:48.272144Z"
    },
    "papermill": {
     "duration": 0.025972,
     "end_time": "2024-03-04T11:02:48.276311",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.250339",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select Mission_Outcome, count(Mission_Outcome) as counts from spacextbl group by Mission_Outcome;\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c130f83",
   "metadata": {
    "papermill": {
     "duration": 0.014474,
     "end_time": "2024-03-04T11:02:48.305440",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.290966",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 8\n",
    "\n",
    "##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5cf1b3e3",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.336836Z",
     "iopub.status.busy": "2024-03-04T11:02:48.336382Z",
     "iopub.status.idle": "2024-03-04T11:02:48.343401Z",
     "shell.execute_reply": "2024-03-04T11:02:48.342248Z"
    },
    "papermill": {
     "duration": 0.02588,
     "end_time": "2024-03-04T11:02:48.346102",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.320222",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select Booster_Version, PAYLOAD_MASS__KG_ from spacextbl where PAYLOAD_MASS__KG_ = (select max(PAYLOAD_MASS__KG_) from spacextbl);"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5a70dfb9",
   "metadata": {
    "papermill": {
     "duration": 0.015065,
     "end_time": "2024-03-04T11:02:48.376213",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.361148",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 9\n",
    "\n",
    "##### List the failed landing_outcomes in drone ship, their booster versions, and launch site names for in year 2015\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6d974cea",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.408851Z",
     "iopub.status.busy": "2024-03-04T11:02:48.408166Z",
     "iopub.status.idle": "2024-03-04T11:02:48.414976Z",
     "shell.execute_reply": "2024-03-04T11:02:48.413868Z"
    },
    "papermill": {
     "duration": 0.02562,
     "end_time": "2024-03-04T11:02:48.417540",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.391920",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select Landing__Outcome, Booster_Version, Launch_Site from spacextbl where Landing__Outcome = 'Failure (drone ship)' and year(Date) = '2015'\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "185074bd",
   "metadata": {
    "papermill": {
     "duration": 0.014529,
     "end_time": "2024-03-04T11:02:48.447219",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.432690",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "### Task 10\n",
    "\n",
    "##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "9cf98598",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-03-04T11:02:48.478939Z",
     "iopub.status.busy": "2024-03-04T11:02:48.478557Z",
     "iopub.status.idle": "2024-03-04T11:02:48.485347Z",
     "shell.execute_reply": "2024-03-04T11:02:48.484184Z"
    },
    "papermill": {
     "duration": 0.02528,
     "end_time": "2024-03-04T11:02:48.487840",
     "exception": false,
     "start_time": "2024-03-04T11:02:48.462560",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/sql/connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "select Landing__Outcome, count(*) as LandingCounts from spacextbl where Date between '2010-06-04' and '2017-03-20' \n",
    "group by Landing__Outcome \n",
    "order by count(*) desc;\n"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [],
   "dockerImageVersionId": 30664,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 67.247881,
   "end_time": "2024-03-04T11:02:49.124729",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2024-03-04T11:01:41.876848",
   "version": "2.5.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
